### PR TITLE
Add authorization support to work with private repositories

### PR DESCRIPTION
**Pull request by DervexDev**
Example:
```curl
curl -H "Authorization: Bearer <GITHUB_TOKEN>" -X GET https://ghloc.ifels.dev/<org>/<private-repo>
```

### CODE REVIEW

**Comment by subtle-byte** [comment]
Hi, I think your PR has an issue - caching is not disabled for private repositories (so potentially someone without token can read locs for your private repository in following request). But without caching the service will work slow, e.g. https://ghloc.vercel.app/ makes new request every time user changes filter. So probably we would need add hash with salt of token as part of cache.

But actually I don't want to work with someone's secrets and this use case looks too rare for me to support it. If you want count locs for private repository you can run the command `go run github.com/subtle-byte/ghloc/cmd/ghloc@latest .`  in the root of your project.

**Comment by DervexDev** [comment]
I'm working on [my Chrome extension](https://github.com/DervexDev/github-loc) that shows you repository LOC so running the command isn't an option here.

> I don't want to work with someone's secrets and this use case looks too rare for me to support it.

I will have to deploy my own ghloc instance then.

**Comment by DervexDev** [comment]
What about disabling caching only for the requests with the `Authorization` header? https://ghloc.vercel.app wouldn't be affected in this case.

**Comment by DervexDev** [comment]
> What about disabling caching only for the requests with the `Authorization` header? https://ghloc.vercel.app wouldn't be affected in this case.

@subtle-byte? I would like to release the extension already, so your response would be really appreciated.

**Comment by subtle-byte** [comment]
> > What about disabling caching only for the requests with the `Authorization` header? https://ghloc.vercel.app wouldn't be affected in this case.
> 
> @subtle-byte? I would like to release the extension already, so your response would be really appreciated.

If just disable caching for requests with token then the locs will be counted every time user opens private repository - it is more load for server. And as I said I don't want to work with someone's secrets and private data. So if you really want to support this I propose to make a fork and deploy it by yourself.

**Comment by DervexDev** [comment]
Fair enough. May I ask where ghloc is currently deployed?

**Comment by subtle-byte** [comment]
It is DigitalOcean currently

**Comment by DervexDev** [comment]
Thanks! I'm thinking of converting this project to work with Vercel serverless functions though.

**Pull request closed without merging**
